pipeline{
    agent any
    environment{
        DOCKER-IMAGE: pranay921/myapp
    }
    stages{
        stage('build'){
            steps{
                dir('newapp'){
                    bat 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                dir('newapp'){
                    bat 'mvn test'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:${BUILD_NUMBER} .'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }
    }
}